const GET_SUSCRIPTIONS_REQUEST = 'GET_SUSCRIPTIONS_REQUEST';
const GET_SUSCRIPTIONS_SUCCESS = 'GET_SUSCRIPTIONS_SUCCESS';
const GET_SUSCRIPTIONS_ERROR = 'GET_SUSCRIPTIONS_ERROR';

const CREATE_SUSCRIPTION_REQUEST = 'CREATE_SUSCRIPTION_REQUEST';
const CREATE_SUSCRIPTION_SUCCESS = 'CREATE_SUSCRIPTION_SUCCESS';
const CREATE_SUSCRIPTION_ERROR = 'CREATE_SUSCRIPTION_ERROR';

const UPDATE_SUSCRIPTION_REQUEST = 'UPDATE_SUSCRIPTION_REQUEST';
const UPDATE_SUSCRIPTION_SUCCESS = 'UPDATE_SUSCRIPTION_SUCCESS';
const UPDATE_SUSCRIPTION_ERROR = 'UPDATE_SUSCRIPTION_ERROR';

const DELETE_SUSCRIPTION_REQUEST = 'DELETE_SUSCRIPTION_REQUEST';
const DELETE_SUSCRIPTION_SUCCESS = 'DELETE_SUSCRIPTION_SUCCESS';
const DELETE_SUSCRIPTION_ERROR = 'DELETE_SUSCRIPTION_ERROR';

const CLEAR_ERRORS = 'CLEAR_ERRORS';

export {
  GET_SUSCRIPTIONS_ERROR, GET_SUSCRIPTIONS_REQUEST, GET_SUSCRIPTIONS_SUCCESS,
  CREATE_SUSCRIPTION_ERROR, CREATE_SUSCRIPTION_SUCCESS, CREATE_SUSCRIPTION_REQUEST,
  DELETE_SUSCRIPTION_ERROR, DELETE_SUSCRIPTION_SUCCESS, DELETE_SUSCRIPTION_REQUEST,
  UPDATE_SUSCRIPTION_ERROR, UPDATE_SUSCRIPTION_SUCCESS, UPDATE_SUSCRIPTION_REQUEST,
  CLEAR_ERRORS,
};
